### ISSUE TITLE
Error on the console while login

### ISSUE THREAD

**Issue by sunnygupta1890** [dcenatiempo/restful-api-from-scratch#1]
/Users/sunngupt/projects/restful-api-from-scratch/lib/handlers.js:347
            var measurements = _perf.getEntriesByType('measure');
                                     ^

TypeError: _perf.getEntriesByType is not a function
    at _data.create.err (/Users/sunngupt/projects/restful-api-from-scratch/lib/handlers.js:347:38)
    at fs.close (/Users/sunngupt/projects/restful-api-from-scratch/lib/data.js:24:15)
    at FSReqWrap.oncomplete (fs.js:169:20)

**Comment by sunnygupta1890** [comment]
@dcenatiempo any idea regarding this.

**Comment by abhijeetshende** [comment]
This method was removed in v10.0.0. 
I installed v8.16.1 and its working for me.
